// generated by stringer -type FSMState constatnt.go; DO NOT EDIT

package bgp

import "fmt"

const _FSMState_name = "BGP_FSM_IDLEBGP_FSM_CONNECTBGP_FSM_ACTIVEBGP_FSM_OPENSENTBGP_FSM_OPENCONFIRMBGP_FSM_ESTABLISHED"

var _FSMState_index = [...]uint8{0, 12, 27, 41, 57, 76, 95}

func (i FSMState) String() string {
	i -= 1
	if i < 0 || i+1 >= FSMState(len(_FSMState_index)) {
		return fmt.Sprintf("FSMState(%d)", i+1)
	}
	return _FSMState_name[_FSMState_index[i]:_FSMState_index[i+1]]
}
