// generated by stringer -type=RouteFamily; DO NOT EDIT

package bgp

import "fmt"

const (
	_RouteFamily_name_0 = "RF_IPv4_UC"
	_RouteFamily_name_1 = "RF_IPv4_MPLS"
	_RouteFamily_name_2 = "RF_IPv4_VPN"
	_RouteFamily_name_3 = "RF_RTC_UC"
	_RouteFamily_name_4 = "RF_IPv6_UC"
	_RouteFamily_name_5 = "RF_IPv6_MPLS"
	_RouteFamily_name_6 = "RF_IPv6_VPN"
)

var (
	_RouteFamily_index_0 = [...]uint8{0, 10}
	_RouteFamily_index_1 = [...]uint8{0, 12}
	_RouteFamily_index_2 = [...]uint8{0, 11}
	_RouteFamily_index_3 = [...]uint8{0, 9}
	_RouteFamily_index_4 = [...]uint8{0, 10}
	_RouteFamily_index_5 = [...]uint8{0, 12}
	_RouteFamily_index_6 = [...]uint8{0, 11}
)

func (i RouteFamily) String() string {
	switch {
	case i == 65537:
		return _RouteFamily_name_0
	case i == 65540:
		return _RouteFamily_name_1
	case i == 65664:
		return _RouteFamily_name_2
	case i == 65668:
		return _RouteFamily_name_3
	case i == 131073:
		return _RouteFamily_name_4
	case i == 131076:
		return _RouteFamily_name_5
	case i == 131200:
		return _RouteFamily_name_6
	default:
		return fmt.Sprintf("RouteFamily(%d)", i)
	}
}
