#
# .goreleaser.yml
# Build customization
builds:
  - main: ./gobgp/
    binary: gobgp
    goos:
      - linux
    goarch:
      - amd64
      - 386
      - arm
      - arm64

  - main: ./gobgpd/
    binary: gobgpd
    goos:
      - linux
    goarch:
      - amd64
      - 386
      - arm
      - arm64

archive:
  files:
    - LICENSE
    - README.md
