#
# .goreleaser.yml
# Build customization
env:
  - GO111MODULE=on

builds:
  - id: gobgp
    main: ./cmd/gobgp/
    binary: gobgp
    ldflags: -s -extldflags "-static"
    goos:
      - linux
    goarch:
      - amd64
      - 386
      - arm
      - arm64

  - id: gobgpd
    main: ./cmd/gobgpd/
    binary: gobgpd
    ldflags: -s -extldflags "-static"
    goos:
      - linux
    goarch:
      - amd64
      - 386
      - arm
      - arm64

archives:
  - id: foo
    files:
      - LICENSE
      - README.md
