#
# .goreleaser.yml
# Build customization
builds:
  - main: ./cmd/gobgp/
    binary: gobgp
    ldflags: -s -extldflags "-static"
    goos:
      - linux
    goarch:
      - amd64
      - 386
      - arm
      - arm64

  - main: ./cmd/gobgpd/
    binary: gobgpd
    ldflags: -s -extldflags "-static"
    goos:
      - linux
    goarch:
      - amd64
      - 386
      - arm
      - arm64

archive:
  files:
    - LICENSE
    - README.md
