// Code generated by "stringer -type=BLACKHOLE_TYPE"; DO NOT EDIT.

package zebra

import "strconv"

const _BLACKHOLE_TYPE_name = "BLACKHOLE_UNSPECBLACKHOLE_NULLBLACKHOLE_REJECTBLACKHOLE_ADMINPROHIB"

var _BLACKHOLE_TYPE_index = [...]uint8{0, 16, 30, 46, 67}

func (i BLACKHOLE_TYPE) String() string {
	if i >= BLACKHOLE_TYPE(len(_BLACKHOLE_TYPE_index)-1) {
		return "BLACKHOLE_TYPE(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _BLACKHOLE_TYPE_name[_BLACKHOLE_TYPE_index[i]:_BLACKHOLE_TYPE_index[i+1]]
}
